In [3]:
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [4]:
#Creating 2D numpy array
matrix = np.array([[1, 2, 3], [3, 4, 5,], [6, 7, 8]], dtype=int)
print(matrix)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [5]:
#Creating Numpy with float elements

array_float = np.array([[1.2, 3.4, 5.6], [2.1, 2.2, 2.3], [3.4, 3.5, 3.6]], dtype = float)
print(array_float)

[[1.2 3.4 5.6]
 [2.1 2.2 2.3]
 [3.4 3.5 3.6]]


In [6]:
#You can also create arrays with predefined values using functions like np.zeros(), np.ones(), np.full(), np.arange(), np.linspace(), etc. 
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
zeros = np.zeros((4, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#Creating an array of ones with shape (3, 2)
ones = np.ones((3, 2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
#Creating an array of a constant value with shape (2, 2)
constant = np.full((2, 2), 9)
print(constant)

[[9 9]
 [9 9]]


In [10]:
#Creating an array of evenely spaced values withing a range
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
b = np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
#with STEPS
c = np.arange(5, 10)
print(c)

d = np.arange(0, 50, 5)
print(d)

[5 6 7 8 9]
[ 0  5 10 15 20 25 30 35 40 45]


In [13]:
#from zero to ten with default number of samples (50)
e = np.linspace(0, 10)
print(e)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [14]:
#Number of samples (5)
f = np.linspace(0, 10, num=5)
print(f)

[ 0.   2.5  5.   7.5 10. ]


In [15]:
#Including the datatype
g = np.linspace(0, 50, num=10, dtype=int)
print(g)

[ 0  5 11 16 22 27 33 38 44 50]


In [ ]:
#Operations with Numpy



In [1]:
#Creating One Dimensional List
import numpy as np
my_array1 = np.array([1, 2, 3, 4, 5], dtype=int)
print(my_array1)

[1 2 3 4 5]


In [2]:
#Creating two dimentionsal Array
my_array2 = np.array([[1.2, 3.4, 5.6], [11.11, 12.12, 13.13]], dtype=float)
print(my_array2)

[[ 1.2   3.4   5.6 ]
 [11.11 12.12 13.13]]


In [5]:
#Crating Array of strings
string_array = (['netra', 'kumar', 'manandhar'])
print(string_array)

['netra', 'kumar', 'manandhar']


In [7]:
#You can also create arrays with predefined values using functions like np.zeros(), np.ones(), np.full(), np.arange(), np.linspace(), etc. For example:
a = np.zeros((2, 4)) #2 rows & 4 columns
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#creating arrays with ones with shapes (3, 4)
b = np.ones((3, 4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
#creating array with a constant values of shape (3, 5)
c = np.full((3, 5), 11)
print(c)

[[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]]


In [10]:
#Creating arrays of evenly spaced values within a range
d = np.arange(10) #from 0 to 9 with space size of 1
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
#from a certain range with step 1
d2 = np.arange(2, 12) #From 2 to 11
print(d2)

[ 2  3  4  5  6  7  8  9 10 11]


In [14]:
#From a constant step other than 1
d3 = np.arange(3, 50, 4) #with the step 4
print(d3)

[ 3  7 11 15 19 23 27 31 35 39 43 47]


In [17]:
d4 = np.arange(0, 50, 2.5)
print(d4)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5
 35.  37.5 40.  42.5 45.  47.5]


In [21]:
#With some default sample size
e1 = np.linspace(0, 15) #Output is 50 float values from 0 to 15.
print(e1)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [22]:
#Fixed Number of samples
e2 = np.linspace(10, 20, num=5) #5 different samples
print(e2)

[10.  12.5 15.  17.5 20. ]


In [25]:
#Fixed sample and data type
e3 = np.linspace(25, 100, num=10, dtype=int) #Sample = 10, data type = Integer value
print(e3)

[ 25  33  41  50  58  66  75  83  91 100]


In [26]:
#Different Functions with Numpy Array

#Arithmetic Operation

In [28]:
#Addition
a = np.array([1, 23, 234, 3453])
b = np.array([21, -23, 343, -2343])
c = np.add(a, b)
print(c)

[  22    0  577 1110]


In [29]:
#Subtract the arrays 
d = np.subtract(a, b)
print(d)

[ -20   46 -109 5796]


In [30]:
#Multiply the arrays
e = np.multiply(a, b)
print(e)

[      21     -529    80262 -8090379]


In [33]:
#Divide the Arrays
f = np.divide(a, b) #Divides a/b
g = np.divide(b, a) #Divides b/a
print(f)
print(g)

[ 0.04761905 -1.          0.68221574 -1.4737516 ]
[21.         -1.          1.46581197 -0.6785404 ]


In [35]:
#Raising the Power
#Integer power is not allowed
x1 = np.array([1, 2, 3, 4])
x2 = np.array([2, 3, 4, 5])
h = np.power(x1, x2) #x1 raised to the power x2
print(h)

[   1    8   81 1024]


**Using Artithmetic Operators

In [39]:
print(a, b)
print(x1, x2)

[   1   23  234 3453] [   21   -23   343 -2343]
[1 2 3 4] [2 3 4 5]


In [40]:
a1 = a+b
print(a1)

[  22    0  577 1110]


In [41]:
a2 = a-b
print(a2)

[ -20   46 -109 5796]


In [42]:
a3 = a*b
print(a3)

[      21     -529    80262 -8090379]


In [43]:
a4 = a/b
print(a4)

[ 0.04761905 -1.          0.68221574 -1.4737516 ]


In [44]:
#Dividing to get output integer value 
a5 = a//b
print(a5)

[ 0 -1  0 -2]


In [45]:
#Raising the Power
a6 = x1**x2
print(a6)

[   1    8   81 1024]


Statistical Operations

In [46]:
stat_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(stat_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [47]:
#Mean
s1 = np.mean(stat_array)
print(s1)

55.0


In [50]:
#Median
s2 = np.median(stat_array)
print(s2)

55.0


In [51]:
#Standard Deviation
s3 = np.std(stat_array)
print(s3)

28.722813232690143


In [52]:
#Variance
s4 = np.var(stat_array)
print(s4)

825.0


In [53]:
#Minimum Values 
s5 = np.min(stat_array)
print(s5)

10


In [54]:
#Maximum Values
s6 = np.max(stat_array)
print(s6)

100


Using Statistics in Multidimensional arrays

In [55]:
multi_array = np.array([[20, 30, 40, 50], [11, 12, 13, 14], [100, 150, 200, 250], [200, 250, 300, 350]])
print(multi_array)

[[ 20  30  40  50]
 [ 11  12  13  14]
 [100 150 200 250]
 [200 250 300 350]]


In [56]:
#Mean of the Row
m1 = np.mean(multi_array, axis=1) #Mean of [20, 30, 40, 50] and so on
print(m1)

[ 35.   12.5 175.  275. ]


In [57]:
#Mean of the Column
m2 = np.mean(multi_array, axis=0) #Mean of [20, 11, 100, 200] and so on
print(m2)

[ 82.75 110.5  138.25 166.  ]


In [59]:
#Median
m3 = np.median(multi_array, axis=1) #Row
m4 = np.median(multi_array, axis=0) #Column
print(m3)
print(m4)

[ 35.   12.5 175.  275. ]
[ 60.  90. 120. 150.]


In [60]:
#Standard Deviation
m5 = np.std(multi_array, axis=1) #Row
m6 = np.std(multi_array, axis=0) #Column
print(m5)
print(m6)

[11.18033989  1.11803399 55.90169944 55.90169944]
[ 76.04398398  96.4403961  117.59756588 139.16896206]


In [61]:
#Variance
m7 = np.var(multi_array, axis=1) #Row
m8 = np.var(multi_array, axis=0) #Column
print(m7)
print(m8)

[1.250e+02 1.250e+00 3.125e+03 3.125e+03]
[ 5782.6875  9300.75   13829.1875 19368.    ]


In [63]:
#Minimum and Maximum value
m9 = np.min(multi_array, axis=1) #Row
m10 = np.min(multi_array, axis=0) #column
print(m9)

print(m10)

[ 20  11 100 200]
[11 12 13 14]


Other important Functions Append, Insert, Delete, Concatenate, etc.

Appending = Adding to the End

In [67]:
#Append in one-dim array
arr = np.array([10, 100, 200, 300, 500, 700])
print(arr)

[ 10 100 200 300 500 700]


In [68]:
#Append a single value to the end
arr1 = np.append(arr, 900) #It will add 900 to the original Array i.e., arr
print(arr1)

[ 10 100 200 300 500 700 900]


In [69]:
#Appending a list of values to the end of the arra
arr2 = np.append(arr, [1100, 1200, 1500])
print(arr2)

[  10  100  200  300  500  700 1100 1200 1500]


In [70]:
#Appending values to two Dim Arrays
two_dim_array = np.array([[10, 20, 30, 40, 50], [5, 15, 25, 35, 45]])
print(two_dim_array)

[[10 20 30 40 50]
 [ 5 15 25 35 45]]


In [71]:
#Appending a single value to the end of each row
arr3 = np.append(two_dim_array, [[60], [55]], axis=1) #Adds the values to the end of each row
print(arr3)

[[10 20 30 40 50 60]
 [ 5 15 25 35 45 55]]


In [72]:
##Appending a list of values to the end of each row
arr4 = np.append(two_dim_array, [[70, 80], [65, 75]], axis=1)
print(arr4)

[[10 20 30 40 50 70 80]
 [ 5 15 25 35 45 65 75]]


In [74]:
#Appending a single value to the end of each column
arr5 = np.append(two_dim_array, [[11, 22, 33, 44, 55]], axis=0) #Note that there are 5 columns in the original column...so need to add 5 elements 
print(arr5)

[[10 20 30 40 50]
 [ 5 15 25 35 45]
 [11 22 33 44 55]]


In [75]:
#Appending a list of values to the end of each column
arr6 = np.append(two_dim_array, [[11, 22, 33, 44, 55], [111, 222, 333, 444, 555]], axis=0)
print(arr6)

[[ 10  20  30  40  50]
 [  5  15  25  35  45]
 [ 11  22  33  44  55]
 [111 222 333 444 555]]


Inserting Values in any Index Values

In [76]:
#np.insert(arr, obj, values, axis=None)

In [77]:
print(arr)

[ 10 100 200 300 500 700]


In [78]:
in1 = np.insert(arr, 2, 55) #Inserting in the second index
print(in1)

[ 10 100  55 200 300 500 700]


In [79]:
in2 = np.insert(arr, 4, 2132213)
print(in2)

[     10     100     200     300 2132213     500     700]


In [81]:
#Adding a list of element
in3 = np.insert(arr, 3, [11, 22, 33])
print(in3)

[ 10 100 200  11  22  33 300 500 700]


In [84]:
#Inserting in multiple index values
in4 = np.insert(arr, [0, 3], [11, 22]) #Inserts the values in index values = 0 and 3
print(in4)
in5 = np.insert(arr, [0, 2, 4], [111, 222, 333])
print(in5)

[ 11  10 100 200  22 300 500 700]
[111  10 100 222 200 300 333 500 700]


In [85]:
#Inserting in Two-Dim Arrays
print(two_dim_array)

[[10 20 30 40 50]
 [ 5 15 25 35 45]]


In [86]:
#Inserting the Values before the first row
new_twod = np.insert(two_dim_array, 0, 0, axis=0)
print(new_twod)

[[ 0  0  0  0  0]
 [10 20 30 40 50]
 [ 5 15 25 35 45]]


In [88]:
#Inserting a list of values before the second column
c1 = np.insert(two_dim_array, 1, [55, 66], axis=1) #Inserts 55 and 66 in the first column index values
print(c1)

[[10 55 20 30 40 50]
 [ 5 66 15 25 35 45]]


In [89]:
c2 = np.insert(two_dim_array, [1, 3], [[22], [33]], axis=1) #Inserts 22 and 33 in the first and third column index
print(c2)

[[10 22 20 30 22 40 50]
 [ 5 33 15 25 33 35 45]]


Concatinating = Joining

In [90]:
a, b

(array([   1,   23,  234, 3453]), array([   21,   -23,   343, -2343]))

In [94]:
#np.concatenate((a1, a2, ...), axis=0)
con1 = np.concatenate((a, b), axis = 0) #Concatenates the arrays in rows
print(con1)

[    1    23   234  3453    21   -23   343 -2343]


In [99]:
con2 = np.concatenate((a, b)) #Default the axis argument is zero
print(con2)

[    1    23   234  3453    21   -23   343 -2343]


In [100]:
#Concatinating two_dim arrays
ar1 = np.array([[2, 3, 4], [4, 5, 6]])
ar2 = np.array([[11, 12, 13], [15, 16, 17]])
print(ar1)
print(ar2)

[[2 3 4]
 [4 5 6]]
[[11 12 13]
 [15 16 17]]


In [101]:
con3 = np.concatenate((ar1, ar2)) #Adding the elements to the ROWS
print(con3)

[[ 2  3  4]
 [ 4  5  6]
 [11 12 13]
 [15 16 17]]


In [104]:
con4 = np.concatenate((ar1, ar2), axis=1) #Adding the elements to the Columns (Increating the number of Columns)
print(con4)

[[ 2  3  4 11 12 13]
 [ 4  5  6 15 16 17]]


Delete Functions

In [105]:
#np.delete(arr, obj, axis=None)

In [106]:
print(arr)

[ 10 100 200 300 500 700]


In [107]:
#To delete a single element by its index value
del1 = np.delete(arr, 2) #Delets the third element i.e., 200
print(del1)

[ 10 100 300 500 700]


In [108]:
#Deleting Multiple elements by their index values
del2 = np.delete(arr, [0, 4]) #Deletes the elements in the first and fifth
print(del2)

[100 200 300 700]


In [111]:
#Delete elements by a boolean mask
del3 = np.delete(arr, arr>100) #Deletes the elements grater than 100 in the array
print(del3)

[ 10 100]


In [112]:
#Delete elements by a boolean mask
del3 = np.delete(arr, arr>500) #Deletes the elements grater than 500 in the array
print(del3)

[ 10 100 200 300 500]


In [115]:
#Deleting elements in two dimensional arrays
print(two_dim_array)

[[10 20 30 40 50]
 [ 5 15 25 35 45]]


In [117]:
#Deleting the first axis
new_array = np.delete(two_dim_array, 0, axis=0)
print(new_array)

[[ 5 15 25 35 45]]


In [118]:
#Deleting the second row of the first axis
new_array1 = np.delete(two_dim_array, 1, axis=0) #1 means = second row 
print(new_array1)

[[10 20 30 40 50]]


In [119]:
#Deleting the Columns
new_array2 = np.delete(two_dim_array, 0, axis=1) #Delets the first columns
print(new_array2)

[[20 30 40 50]
 [15 25 35 45]]


In [120]:
#Deleting third columns
new_array3 = np.delete(two_dim_array, 2, axis=1)
print(new_array3)

[[10 20 40 50]
 [ 5 15 35 45]]
