In [5]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [12]:
a = np.array([1, 2, 3])
b = [11, 22, 33]
#Copypto method 
np.copyto(a, b)
print(a)

[11 22 33]


In [13]:
a1 = np.array([[10, 11, 12], [111, 222, 333]])
b1 = [[100, 200, 300], [400, 500, 600]]
np.copyto(a1, b1)
print(a1)

[[100 200 300]
 [400 500 600]]


In [14]:
#Broadcsting a scalar to an array
arr = np.array([1, 2, 3, 4, 5])
scalar = 100
result = arr + scalar
print(result)

[101 102 103 104 105]


In [17]:
#array concatenation
a1 = np.array([11, 22, 33])
b1 = np.array([100, 200, 300])
concatenated = np.concatenate((a1, b1)) #Concatenate along the rows (axis = 0)
print(concatenated)

[ 11  22  33 100 200 300]


In [18]:
#concatenating along the column (axis = 1)
concatenated_column = np.column_stack((a1, b1))
print(concatenated_column)

[[ 11 100]
 [ 22 200]
 [ 33 300]]


In [19]:
#Splitting the Array
print(arr)

[1 2 3 4 5]


In [20]:
split_arr = np.array_split(arr, 2)
print(split_arr)

[array([1, 2, 3]), array([4, 5])]


In [21]:
arr1 = np.array([1, 2, 3, 4, 5])
index = np.array([0, 2, 4])
result = arr1[index]
print(result)

[1 3 5]


In [22]:
#Indexing using a boolean mask
mask = arr>3
result_mased = arr[mask]
print(result_mased)

[4 5]


In [24]:
#Vectorized Function
arr2 = np.array([10, 20, 30, 40, 50])
#Define a custom function
def custom_function(x):
    return x**3
result = np.vectorize(custom_function)(arr2)
print(result)

[  1000   8000  27000  64000 125000]
