In [1]:
import numpy as np

In [2]:
#Creating Arrays
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [8]:
#special Cases 
ones = np.ones(4, int)
ones2 = np.ones(4, float)
print(ones)
print(ones2)

[1 1 1 1]
[1. 1. 1. 1.]


In [19]:
zeros = np.zeros(3, int)
print(zeros)

[0 0 0]


In [22]:
#Random Values Generation
rand1 = np.random.random(3)
print(rand1)

[0.73587454 0.50060619 0.10611891]


Array Arithmetic

In [24]:
arr2 = np.array([11, 22])
arr3 = np.array([55, 66])
add = arr2 + arr3
print(add)

[66 88]


In [27]:
data1 = np.array([2, 3], int)
data2 = np.ones(2, int)
add1 = data1+data2
print(add1)

[3 4]


In [28]:
#Subtract
subtract = data1 - data2 
print(subtract)

[1 2]


In [29]:
#Multiply
multiply = data1*data2
print(multiply)

[2 3]


In [30]:
#Divide
divide = data1*data2
print(divide)

[2 3]


In [31]:
#Dividing by a specific numbers
divide1 = data1/1.6
print(divide1)

[1.25  1.875]


In [32]:
#Multiplying by a specific number
multiply2 = data1*100
print(multiply2)

[200 300]


In [33]:
#Indexing the Array
arr3 = np.array([11, 22, 33, 44, 55, 66])
i1 = arr3[2]
print(i1)

33


In [35]:
#Indexing Range
i2 = arr3[2:6]
print(i2)

[33 44 55 66]


In [37]:
#Indexing the last value
i3 = arr3[-1]
print(i3)

66


In [38]:
#Indexing from one step to last
i4 = arr3[2:] #prints all the values from third position
print(i4)

[33 44 55 66]


Aggregation

In [40]:
#Maximum and Miminum Values 
max_value = arr3.max()
min_vaalue = arr3.min()
print(max_value)
print(min_vaalue)

66
11


In [41]:
#Total Sum
sum_value = arr3.sum()
print(sum_value)

231


In [43]:
#Other statistical values
mean_value = arr3.mean()
Std_value = arr3.std()
product_value = arr3.prod()
print(mean_value,  Std_value, product_value)

38.5 18.786076404259266 1275523920


In [44]:
#Creating 2-D array 
arr4 = np.array([[11, 22], [33, 44]])
print(arr4)

[[11 22]
 [33 44]]


In [45]:
#Creating Matrices
arr5 = np.array([[10, 20], [30, 40]])
print(arr5)

[[10 20]
 [30 40]]


In [51]:
#Ones
ones3 = np.ones((3, 2), int) #Creates matrix of 3*2
print(ones3)

[[1 1]
 [1 1]
 [1 1]]


In [52]:
ones4 = np.ones((3, 2), float)
print(ones4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [53]:
#Zeros
zeros2 = np.zeros((3, 2))
print(zeros2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [54]:
#Random Values
rand2 = np.random.random((3, 2))
print(rand2)

[[0.19398939 0.62725107]
 [0.25289491 0.61421523]
 [0.47344642 0.30273351]]


Matrix Arithmetic

In [59]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print(m1)
print(m2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [60]:
#addition
add2 = m1 + m2
print(add2)

[[ 6  8]
 [10 12]]


In [62]:
m3 = np.array([2, 3])
add3 = m1+m3 #NumPy makes one dimension to [[2, 3], [2, 3]] and performs the addition operation, This is called broadcasting 
print(add3)

[[3 5]
 [5 7]]


In [65]:
#Other arithmetic operation
multiply = m1*m2
print(multiply) #It is not a matrix multiplication, it multplies respective elements in the matrices
divide = m1/m2
print(divide)


[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [66]:
#Dot Product (Matrix Multiplication)
dot_product = m1.dot(m2)
print(dot_product)

[[19 22]
 [43 50]]


In [67]:
#Matrix Indexing 
m3 = np.array([[11, 22], [33, 44], [55, 66]])
print(m3)

[[11 22]
 [33 44]
 [55 66]]


In [70]:
i1 = m3[0, 1]
print(i1)

22


In [73]:
i2 = m3[1:3]
print(i2)

[[33 44]
 [55 66]]


In [81]:
i3 = m3[0:3, 0]
print(i3)

[11 33 55]


Matrix Aggregation

In [82]:
max_value = m3.max()
min_value = m3.min()
print(max_value)
print(min_vaalue)

66
11


In [83]:
sum_value = m3.sum()
print(sum_value)

231


In [85]:
#From Rows and Columns
max_value1 = m3.max(axis=0) #Maximum values from the Rows
print(max_value1)

[55 66]


In [86]:
max_values_columns = m3.max(axis=1)
print(max_values_columns)

[22 44 66]


Transposing and Reshaping

In [87]:
#Reshaping can be done into the number of pair of its factors...For eg., 1*6 matrix has three pairs: 1*6, 2*3 or 3*2, and 6*1
m4 = np.array([11, 22, 33, 44, 55, 66])
reshape_matrix = m4.reshape(2, 3)
print(reshape_matrix)

[[11 22 33]
 [44 55 66]]


In [88]:
reshape_matrix1 = m4.reshape(3, 2)
print(reshape_matrix1)

[[11 22]
 [33 44]
 [55 66]]


In [90]:
reshape_matrix2 = m4.reshape(6, 1)
print(reshape_matrix2)

[[11]
 [22]
 [33]
 [44]
 [55]
 [66]]


More Dimensions

In [91]:
nd1 = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(nd1)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [93]:
var1 = np.matrix([[1, 2], [3, 4]])
var2 = np.matrix([[5, 6], [7, 8]])
multiply = var1*var2 #Performs matrix mulplication 
print(multiply)

[[19 22]
 [43 50]]


In [94]:
print(type(var1))

<class 'numpy.matrix'>


In [95]:
ones11 = np.ones((4, 3, 2))
print(ones11)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [97]:
zeros11 = np.zeros((3, 4, 2))
print(zeros11)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [99]:
rand3 = np.random.random((4, 3, 2))
print(rand3.shape)
print(rand3)

(4, 3, 2)
[[[0.79311412 0.10953726]
  [0.16877503 0.11841454]
  [0.96035888 0.86122021]]

 [[0.87282808 0.35164514]
  [0.0964172  0.32462054]
  [0.34441031 0.04511703]]

 [[0.37776916 0.44478574]
  [0.03099672 0.4194451 ]
  [0.17486022 0.21538718]]

 [[0.9696311  0.81082757]
  [0.70632029 0.77675916]
  [0.16391229 0.19661636]]]
